Repository bloomberg/chef-bach, pull requests merged in 2018-04, with the labels that each got.

#1155 add a function to get ip list of head nodes
  cookbooks/bcpc/libraries/utils.rb
  cookbooks/bcpc/recipes/certs.rb
Labels: Chef, Ready to Review, bug, to-backport

#1156 Licensing info badge for README.md
  README.md
Labels: Documentation, Tested

#1149 Rollup of changes from dev Kafka
  cookbooks/bcpc-hadoop/attributes/default.rb
  cookbooks/bcpc-hadoop/attributes/jolokia.rb
  cookbooks/bcpc-hadoop/recipes/maven_config.rb
  cookbooks/bcpc-hadoop/recipes/ssl_configuration.rb
  cookbooks/bcpc-hadoop/recipes/zookeeper_impl.rb
  cookbooks/bcpc-hadoop/recipes/zookeeper_server.rb
  cookbooks/bcpc-hadoop/templates/default/zk_zookeeper-env.sh.erb
  cookbooks/bcpc_kafka/recipes/kafka.rb
  cookbooks/bcpc_kafka/recipes/zookeeper_server.rb
Labels: Kafka, Zookeeper

#1158 Enable table level region balancing
  cookbooks/bcpc-hadoop/attributes/hbase.rb
Labels: Builds, HBase, Ready To Merge, Ready to Review, Tested, enhancement

#1147 Make the shell script vbox_create.sh a bit more readable
  vbox_create.sh
Labels: Ready to Review, Shell Script, Tested

#1160 Change to enable user to set custom Kafka znode
  cookbooks/bcpc_kafka/attributes/default.rb
  cookbooks/bcpc_kafka/recipes/kafka.rb
Labels: Kafka, Ready to Review, enhancement

#1162 Change to enable users to set Kafka broker.rack property
  cookbooks/bcpc_kafka/attributes/default.rb
  cookbooks/bcpc_kafka/recipes/kafka.rb
Labels: Kafka, Ready to Review, Tested, enhancement

#1121 Ambari Views Integration
  .gitignore
  Berksfile
  cookbooks/ambari/.gitignore
  cookbooks/ambari/.kitchen.yml
  cookbooks/ambari/Berksfile
  cookbooks/ambari/README.md
  cookbooks/ambari/attributes/default.rb
  cookbooks/ambari/chefignore
  cookbooks/ambari/files/default/hortonworks.key
  cookbooks/ambari/libraries/utils.rb
  cookbooks/ambari/metadata.rb
  cookbooks/ambari/notes
  cookbooks/ambari/recipes/ambari_server_install.rb
  cookbooks/ambari/recipes/ambari_server_setup.rb
  cookbooks/ambari/recipes/ambari_views_setup.rb
  cookbooks/ambari/recipes/default.rb
  cookbooks/ambari/recipes/postgres_server_embedded_setup.rb
  cookbooks/ambari/spec/spec_helper.rb
  cookbooks/ambari/spec/unit/recipes/ambari_server_setup_spec.rb
  cookbooks/ambari/spec/unit/recipes/ambari_views_setup_spec.rb
  cookbooks/ambari/spec/unit/recipes/default_spec.rb
  cookbooks/ambari/templates/default/ambari.properties.erb
  cookbooks/ambari/templates/default/krb5JAASLogin.conf.erb
  cookbooks/ambari/templates/default/password.dat.erb
  cookbooks/ambari/test/integration/default/serverspec/default_spec.rb
  cookbooks/ambari/test/integration/helpers/serverspec/spec_helper.rb
  cookbooks/bach_ambari/.gitignore
  cookbooks/bach_ambari/.kitchen.yml
  cookbooks/bach_ambari/Berksfile
  cookbooks/bach_ambari/README.md
  cookbooks/bach_ambari/attributes/default.rb
  cookbooks/bach_ambari/chefignore
  cookbooks/bach_ambari/metadata.rb
  cookbooks/bach_ambari/recipes/default.rb
  cookbooks/bach_ambari/recipes/mysql_server_external_setup.rb
  cookbooks/bach_ambari/recipes/remove_sensitive_attributes.rb
  cookbooks/bach_ambari/spec/spec_helper.rb
  cookbooks/bach_ambari/spec/unit/recipes/default_spec.rb
  cookbooks/bach_ambari/test/smoke/default/default_test.rb
  cookbooks/bcpc-hadoop/attributes/core.rb
  cookbooks/bcpc-hadoop/attributes/default.rb
  cookbooks/bcpc-hadoop/attributes/kerberos.rb
  cookbooks/bcpc-hadoop/attributes/yarn.rb
  cookbooks/bcpc-hadoop/libraries/utils.rb
  cookbooks/bcpc-hadoop/recipes/yarn_site.rb
  cookbooks/bcpc-hadoop/templates/default/ooz_oozie-site.xml.erb
  cookbooks/bcpc/attributes/default.rb
  cookbooks/bcpc/recipes/mysql_data_bags.rb
  cookbooks/bcpc/templates/default/haproxy.cfg.erb
  stub-environment/hadoop_cluster.txt
  stub-environment/roles/BACH-Ambari-Server.json
Labels: HDFS, RFC, Ready to Review, Test, Tested, enhancement

#1167 Properly backport #1155 to 3.3.x
  cookbooks/bcpc/libraries/utils.rb
Labels: Backport, Chef, Tested, bug

#1168 Track cookbooks
  .gitignore
Labels: Chef

#1169 Add hannibal to bins
  cookbooks/bach_repository/attributes/hannibal.rb
  cookbooks/bach_repository/recipes/hannibal.rb
Labels: Ready To Merge, Ready to Review, Tested, enhancement

#1041 Changes for Hannibal
  .gitignore
  Berksfile
  cookbooks/bach_hannibal/README.md
  cookbooks/bach_hannibal/metadata.rb
  cookbooks/bach_hannibal/recipes/default.rb
  cookbooks/bach_hannibal/recipes/hannibaldb.rb
  cookbooks/bach_hannibal/recipes/hannibalhb.rb
  cookbooks/bach_hannibal/recipes/mysql_link.rb
  cookbooks/hannibal/attributes/default.rb
  cookbooks/hannibal/recipes/default.rb
  cookbooks/hannibal/recipes/hannibal_build.rb
  cookbooks/hannibal/recipes/hannibal_deploy.rb
  cookbooks/hannibal/recipes/hannibal_service.rb
  cookbooks/hannibal/spec/spec_helper.rb
  cookbooks/hannibal/spec/support/matchers.rb
  cookbooks/hannibal/spec/tests/hannibal_build_tarball_doesnt_exist_spec.rb
  cookbooks/hannibal/spec/tests/hannibal_build_tarball_exists_spec.rb
  cookbooks/hannibal/spec/tests/hannibal_deploy_spec.rb
  cookbooks/hannibal/templates/default/generic_site.xml.erb
  cookbooks/hannibal/templates/default/hannibal.upstart.conf.erb
  cookbooks/hannibal/templates/default/hannibal_application.conf.erb
  cookbooks/hannibal/templates/default/hannibal_hbase-site.xml.erb
  cookbooks/hannibal/templates/default/hannibal_init.rb
  stub-environment/roles/BACH-Hannibal.json
  stub-environment/roles/Hannibal-Build.json
Labels: Builds, HBase, Ready To Merge, Ready to Review, Tested, enhancement

#1170 Changes to enable users to use non default ZK port for Kafka
  cookbooks/bcpc_kafka/recipes/kafka.rb
Labels: Tested, Zookeeper, enhancement

#1164 Hive CRUD smoke tests
  cookbooks/bcpc-hadoop/recipes/smoke_test_wrapper.rb
  cookbooks/smoke-tests/recipes/oozie_smoke_test.rb
  cookbooks/smoke-tests/templates/default/hive_smoke_test.hql.erb
  cookbooks/smoke-tests/templates/default/smoke_test_job_properties.erb
  cookbooks/smoke-tests/templates/default/smoke_test_xml.erb
Labels: Hive, Metrics/Alarming, Tested, enhancement

#1178 Use maven central and a default trust store
  cookbooks/bcpc-hadoop/attributes/maven.rb
  cookbooks/bcpc-hadoop/recipes/maven_config.rb
  cookbooks/bcpc-hadoop/recipes/ssl_configuration.rb
Labels: Chef, Ready to Review, Tested, bug

#1177 Namenode Ids instead of nodenumbers
  cookbooks/bach_ambari/recipes/default.rb
Labels: Tested, bug

#1174 Enable users to use non chef-bach ZooKeeper for Kafka
  cookbooks/bcpc_kafka/attributes/default.rb
  cookbooks/bcpc_kafka/recipes/kafka.rb
Labels: Zookeeper, enhancement

#1179 --no-use-wheel is deprecated
  cookbooks/bach_repository/recipes/python.rb
Labels: Chef, Ready to Review, Tested, bug

#1173 refactored datanode and journalnode ports into attributes.
  cookbooks/bcpc-hadoop/attributes/hdfs.rb
  cookbooks/bcpc-hadoop/attributes/journalnode.rb
  cookbooks/bcpc-hadoop/recipes/hdfs_site.rb
Labels: HDFS, Hadoop, Refactor, Tested

#1171 Measure the root queue metrics
  cookbooks/bcpc-hadoop/attributes/jmxtrans_agent.rb
Labels: Metrics/Alarming, YARN

#1190 Clean-up unused whisper metric directories
  cookbooks/bcpc/recipes/graphite.rb
Labels: Metrics/Alarming

#1189 Remove errant impala startup file
  cookbooks/bcpc-hadoop/templates/default/impala.start.erb
Labels: Tested
