Repository bloomberg/chef-bach, pull requests merged in 2018-12, with the labels that each got.

#1320 Drop flume (copylog)
  README.md
  cookbooks/bcpc-hadoop/attributes/default.rb
  cookbooks/bcpc-hadoop/attributes/kerberos.rb
  cookbooks/bcpc-hadoop/recipes/copylog.rb
  cookbooks/bcpc-hadoop/recipes/datanode.rb
  cookbooks/bcpc-hadoop/recipes/hbase_master.rb
  cookbooks/bcpc-hadoop/recipes/namenode_master.rb
  cookbooks/bcpc-hadoop/recipes/namenode_no_HA.rb
  cookbooks/bcpc-hadoop/recipes/namenode_standby.rb
  cookbooks/bcpc-hadoop/recipes/region_server.rb
  cookbooks/bcpc-hadoop/templates/default/flume_flume-agent.erb
  cookbooks/bcpc-hadoop/templates/default/flume_flume-conf.erb
  cookbooks/bcpc-hadoop/templates/default/flume_flume-env.sh.erb
  cookbooks/bcpc-hadoop/templates/default/flume_log4j.properties.erb
  spec/unit/cluster_data.rb
Labels: Builds, Flume, Tested

#1321 Drop JMXtrans cookbook
  Berksfile
  Berksfile.common
  cookbooks/bcpc_jmxtrans/README.md
  cookbooks/bcpc_jmxtrans/attributes/default.rb
  cookbooks/bcpc_jmxtrans/chefignore
  cookbooks/bcpc_jmxtrans/libraries/utils.rb
  cookbooks/bcpc_jmxtrans/metadata.rb
  cookbooks/bcpc_jmxtrans/recipes/default.rb
  cookbooks/bcpc_kafka/metadata.rb
  metadata.rb
  spec/unit/cluster_data.rb
Labels: Builds, Tested

#1323 Update Grub configuration to allow toggling of legacy NIC names
  cookbooks/bcpc/recipes/grub.rb
  cookbooks/bcpc/templates/default/grub/etc_default_grub.erb
Labels: Bug, Operating System, to-backport

#1324 Split chef clients
  cookbooks/bcpc/attributes/chef_client.rb
  cookbooks/bcpc/recipes/bootstrap_knife.rb
  cookbooks/bcpc/recipes/chef_client.rb
  lib/chef_node.rb
  setup_chef_bootstrap_node.sh
  setup_chef_cookbooks.sh
  stub-environment/environments/Test-Laptop.json
Labels: Chef, Hypervisor, Tested

#1326 Allow disabling of DHCP for whole subnets
  cookbooks/bcpc/recipes/cobbler.rb
Labels: Operating System, Tested, to-backport

#1327 Call the new kdc_init recipe
  cookbooks/bach_krb5/recipes/krb5_server.rb
Labels: Ready to Review, Tested, Upstream, to-backport

#1329 Set datanode activity metrics as gauges
  cookbooks/bcpc-hadoop/attributes/jmxtrans_agent.rb
Labels: Bug, Metrics/Alarming, to-backport
