Repository bloomberg/chef-bach, pull requests merged in 2018-11, with the labels that each got.

#1297 Fix select_bach_root_disk script and add support for using NVMe volumes when no other options are present
  cookbooks/bcpc/templates/default/cobbler/select_bach_root_disk.erb
Labels: Bug, Operating System, Tested, to-backport

#1299 add yarn to hadoop proxyuser
  cookbooks/bcpc-hadoop/attributes/core.rb
Labels: Bug, HDFS, Hadoop, Ready to Review, to-backport

#1305 Copy jce policy to the chef filecache
  cookbooks/bach_repository/recipes/oracle_java.rb
Labels: Bug, Tested

#1306 BF: fix reference to dir_creation group attribute
  cookbooks/bcpc-hadoop/files/default/create_dirs.rb
Labels: Bug, Tested, to-backport

#1303 Fix the zookeeper environment jvm flags.
  cookbooks/bcpc-hadoop/templates/default/zk_zookeeper-env.sh.erb
Labels: Bug, Chef, Ready To Merge, Zookeeper

#1307 Use linked cloning for VM images
  Vagrantfile
Labels: Hypervisor

#1311 Enable grub/serial tty configuration management (redux)
  cookbooks/bcpc/attributes/default.rb
  cookbooks/bcpc/recipes/grub.rb
  cookbooks/bcpc/templates/default/grub/etc_default_grub.erb
  cookbooks/bcpc/templates/default/grub/ttySX.conf.erb
Labels: Bug, Enhancement, Operating System, to-backport

#1309 Use proper certificates for the chef-server
  bootstrap_chef.sh
  cluster-enroll-cobbler.sh
  deploy_cookbooks.sh
  proxy_setup.sh
  setup_chef_bootstrap_node.sh
  setup_chef_cookbooks.sh
  setup_chef_server.sh
  vbox_create.sh
Labels: Builds, Chef

#1313 Document vagrant
  README.md
  bootstrap.md
  windows.md
Labels: Documentation

#1316 codify vagrant+virtualbox network hacks
  cookbooks/bcpc/recipes/networking.rb
  nodessh.sh
Labels: Bug, Builds, Tested

#1317 Drop diamond
  cookbooks/bach_repository/recipes/default.rb
  cookbooks/bach_repository/recipes/diamond.rb
  cookbooks/bcpc-hadoop/recipes/graphite_queries.rb
  cookbooks/bcpc/attributes/diamond.rb
  cookbooks/bcpc/recipes/diamond.rb
  cookbooks/bcpc/templates/default/diamond.conf.erb
  cookbooks/bcpc/templates/default/keepalived-vip_change.erb
  stub-environment/roles/BCPC-Hadoop-Head-HBase.json
Labels: Builds, Tested
