Repository bloomberg/chef-bach, pull requests merged in 2018-03, with the labels that each got.

#1128 Update service name for kafka broker
  cookbooks/bcpc_kafka/recipes/kafka.rb
Labels: Chef, Kafka, Tested

#1060 Travis Style Check Support
  .rubocop.yml
  .travis.yml
  Gemfile
  Rakefile
  compare_style.sh
Labels: Chef, Ready to Review, Ruby, Test, Tools

#1130 Run the oozie workarounds only once
  cookbooks/bcpc-hadoop/recipes/oozie.rb
  stub-environment/hadoop_cluster.txt
Labels: Oozie, bug

#1119 HBase Whitelist Coprocessors and Use locking_resource
  cookbooks/bcpc-hadoop/attributes/hbase.rb
  cookbooks/bcpc-hadoop/definitions/hadoop_service.rb
  cookbooks/bcpc-hadoop/recipes/hbase_config.rb
  cookbooks/bcpc-hadoop/recipes/hbase_master.rb
  cookbooks/bcpc-hadoop/recipes/region_server.rb
Labels: Builds, Chef, HBase, Tested

#1136 BACH-1110 Enable Phoenix ACL
  cookbooks/bcpc-hadoop/recipes/hbase_config.rb
Labels: Phoenix, enhancement

#1134 update carbon.conf to match graphite-1.1.1
  cookbooks/bcpc/templates/default/carbon/carbon.conf.erb
Labels: Metrics/Alarming, Ready to Review, Tested, enhancement

#1079 Add Phoenix properties to enable Phoenix namespace mapping
  cookbooks/bcpc-hadoop/attributes/hbase.rb
Labels: Breaking, DeploymentWarning, Phoenix, Ready to Review

#1142 added hadoop.security.dns.interface to resolve issue # 1125
  cookbooks/bcpc-hadoop/recipes/core_site.rb
Labels: Builds, HDFS, Hadoop, Ready To Merge, Ready to Review, Tested, enhancement

#1133 Jenkinsfile to check lint improvements in PRs
  Jenkinsfile
  Rakefile
Labels: Ready to Review, Test

#1140 Changes to enable HBase regionserver groups
  cookbooks/bcpc-hadoop/attributes/hbase.rb
  cookbooks/bcpc-hadoop/recipes/hbase_config.rb
Labels: HBase, Tested

#1141 Fix node_number referencing for YARN
  cookbooks/bcpc-hadoop/recipes/yarn_site.rb
Labels: Tested, bug

#1138 save the queries to normal precedence, to replace previously saved ones.
  cookbooks/bcpc-hadoop/recipes/journalnode_queries.rb
Labels: Metrics/Alarming, Tested, bug

#1145 Remove duplicate code to check vagrant availability
  vbox_create.sh
Labels: enhancement

#1146 Add node id to kafka_cluster.txt
  stub-environment/kafka_cluster.txt
Labels: bug

#1123 Fix ssl certificate issue
  cookbooks/bcpc/attributes/certs.rb
  cookbooks/bcpc/attributes/default.rb
  cookbooks/bcpc/recipes/certs.rb
  cookbooks/bcpc/recipes/networking.rb
  cookbooks/bcpc/recipes/ssh_cert_deploy.rb
  cookbooks/bcpc/recipes/ssl_cert_deploy.rb
  cookbooks/bcpc/templates/default/apache-000-default.erb
  cookbooks/bcpc/templates/default/apache-graphite-web.conf.erb
  cookbooks/bcpc/templates/default/apache-zabbix-web.conf.erb
  cookbooks/bcpc/templates/default/authorized_keys.erb
  cookbooks/bcpc/templates/default/bach_openssl.cnf.erb
  cookbooks/bcpc/templates/default/id_rsa.erb
  cookbooks/bcpc/templates/default/libvirtd.conf.erb
  cookbooks/bcpc/templates/default/ssl-bcpc.crt.erb
  cookbooks/bcpc/templates/default/ssl-bcpc.key.erb
  stub-environment/roles/BCPC-Bootstrap.json
  stub-environment/roles/BCPC-Hadoop-Head.json
  stub-environment/roles/Basic.json
Labels: Chef, Tested, bug

#1143 Reindex by hand
  cluster_assign_roles.rb
  lib/chef_node.rb
  setup_chef_server.sh
Labels: Chef, Tested, bug, enhancement

#1148 avoid duplicated javaagent in jvm opts
  cookbooks/bcpc-hadoop/attributes/hbase.rb
  cookbooks/bcpc-hadoop/recipes/hbase_env.rb
  cookbooks/bcpc-hadoop/templates/default/hdp_hadoop-env.sh.erb
  cookbooks/bcpc-hadoop/templates/default/hdp_hbase-env.sh.erb
Labels: Ready to Review, Tested, to-backport

#1150 Fix errant single quotes on not_if in namenode_master.rb
  cookbooks/bcpc-hadoop/recipes/namenode_master.rb
Labels: Chef, HDFS, bug

#1151 need to add '--fresh' when update ca-certificates
  cookbooks/bcpc/recipes/ssl_cert_deploy.rb
Labels: Operating System, Tested, bug, to-backport

#1153 Remove '-R' for hive-scratch dir.
  cookbooks/bcpc-hadoop/recipes/hive_hcatalog.rb
Labels: Hive, bug
