Repository bloomberg/chef-bach, pull requests merged in 2018-09, with the labels that each got.

#1267 Refactor dir creation
  cookbooks/bcpc-hadoop/attributes/dir_creation.rb
  cookbooks/bcpc-hadoop/attributes/hdfs.rb
  cookbooks/bcpc-hadoop/files/default/create_dirs.rb
  cookbooks/bcpc-hadoop/files/default/create_projects_dirs.rb
  cookbooks/bcpc-hadoop/libraries/dir_creation.rb
  cookbooks/bcpc-hadoop/libraries/projects_dir_creation.rb
  cookbooks/bcpc-hadoop/recipes/hdfs_group_directories.rb
  cookbooks/bcpc-hadoop/recipes/hdfs_project_directories.rb
  cookbooks/bcpc-hadoop/recipes/hdfs_user_directories.rb
Labels: HBase, HDFS, Ruby, WIP, to-backport

#1266 Add bach web portal page
  cookbooks/bcpc-hadoop/attributes/hbase.rb
  cookbooks/bcpc-hadoop/attributes/hdfs.rb
  cookbooks/bcpc-hadoop/recipes/hadoop_config.rb
  cookbooks/bcpc-hadoop/recipes/hbase_config.rb
  cookbooks/bcpc-hadoop/recipes/hbase_web.rb
  cookbooks/bcpc-hadoop/recipes/hdfs_web.rb
  cookbooks/bcpc-hadoop/templates/default/regexlist.conf.erb
  cookbooks/bcpc/attributes/apache2.rb
  cookbooks/bcpc/recipes/apache-mirror.rb
  cookbooks/bcpc/recipes/apache2.rb
  cookbooks/bcpc/templates/default/bach-web.conf.erb
  cookbooks/bcpc/templates/default/bach.html.erb
Labels: Enhancement, Ready to Review, to-backport

#1269 add attributes support to haproxy
  cookbooks/bach_ambari/recipes/default.rb
  cookbooks/bcpc-hadoop/attributes/hbase.rb
  cookbooks/bcpc-hadoop/attributes/oozie.rb
  cookbooks/bcpc-hadoop/libraries/utils.rb
  cookbooks/bcpc-hadoop/recipes/oozie_client.rb
  cookbooks/bcpc/attributes/apache2.rb
  cookbooks/bcpc/attributes/default.rb
  cookbooks/bcpc/recipes/haproxy.rb
  cookbooks/bcpc/templates/default/haproxy.cfg.erb
Labels: Enhancement, Ready to Review, Tested

#1272 Fix the 'ssh failed to start error' on every chef run.
  cookbooks/bcpc/recipes/ssh.rb
Labels: Tested, to-backport

#1273 Update Ubuntu mini-iso checksum for the September 12th update
  cookbooks/bach_repository/recipes/ubuntu.rb
Labels: Upstream

#1277 Disable bucket cache on HBase masters
  cookbooks/bcpc-hadoop/recipes/hbase_config.rb
  cookbooks/bcpc-hadoop/recipes/hbase_env.rb
Labels: Bug, DeploymentWarning, HBase, Tested, to-backport

#1279 Add AggregateImplementation class
  cookbooks/bcpc-hadoop/recipes/hbase_config.rb
Labels: Bug, HBase, Ready To Merge, Ready to Review, Tested, to-backport

#1281 [jRuby] - Allow floating points in quotas
  cookbooks/bcpc-hadoop/files/default/create_dirs.rb
Labels: Bug, Enhancement, to-backport

#1282 re-organize bach_web json page
  cookbooks/bcpc-hadoop/attributes/hbase.rb
  cookbooks/bcpc-hadoop/attributes/hdfs.rb
  cookbooks/bcpc-hadoop/recipes/hbase_web.rb
  cookbooks/bcpc-hadoop/recipes/hdfs_web.rb
  cookbooks/bcpc/attributes/apache2.rb
  cookbooks/bcpc/recipes/apache2.rb
  cookbooks/bcpc/templates/default/bach.html.erb
Labels: Enhancement, Ready to Review, Tested
