Repository bloomberg/chef-bach, pull requests merged in 2018-08, with the labels that each got.

#1250 add graphite blacklist configs
  cookbooks/bcpc/attributes/graphite.rb
  cookbooks/bcpc/recipes/graphite.rb
  cookbooks/bcpc/templates/default/carbon/blacklist.conf.erb
  cookbooks/bcpc/templates/default/carbon/carbon.conf.erb
Labels: Enhancement, Metrics/Alarming, Tested, to-backport

#1251 Graphite add blacklist (updated)
  cookbooks/bcpc/attributes/graphite.rb
  cookbooks/bcpc/recipes/graphite.rb
  cookbooks/bcpc/templates/default/carbon/blacklist.conf.erb
Labels: Bug, Tested

#1252 Set more metrics to be gauges
  cookbooks/bcpc-hadoop/attributes/jmxtrans_agent.rb
Labels: HBase

#1254 fix ldapsearch for hdfs dir creation
  cookbooks/bcpc-hadoop/attributes/hdfs.rb
  cookbooks/bcpc-hadoop/attributes/ldap.rb
  cookbooks/bcpc-hadoop/attributes/maintenance.rb
  cookbooks/bcpc-hadoop/files/default/create_dirs.rb
  cookbooks/bcpc-hadoop/libraries/dir_creation.rb
  cookbooks/bcpc-hadoop/libraries/find_object_by_group.rb
  cookbooks/bcpc-hadoop/libraries/helpers.rb
  cookbooks/bcpc-hadoop/libraries/ldap_search.rb
  cookbooks/bcpc-hadoop/libraries/membership.rb
  cookbooks/bcpc-hadoop/recipes/core_site.rb
  cookbooks/bcpc-hadoop/recipes/hdfs_group_directories.rb
  cookbooks/bcpc-hadoop/recipes/hdfs_user_directories.rb
Labels: Enhancement, Tested, to-backport

#1255 utilize the quota_reset hdfs constant
  cookbooks/bcpc-hadoop/files/default/create_dirs.rb
Labels: HDFS, Tested, to-backport

#1257 fix role account filter
  cookbooks/bcpc-hadoop/libraries/ldap_search.rb
Labels: Tested, to-backport

#1259 Copy jRuby users/groups script to new projects one
  cookbooks/bcpc-hadoop/attributes/hdfs.rb
  cookbooks/bcpc-hadoop/files/default/create_projects_dirs.rb
  cookbooks/bcpc-hadoop/libraries/projects_dir_creation.rb
  cookbooks/bcpc-hadoop/recipes/hdfs_project_directories.rb
Labels: HBase, HDFS, Tested, to-backport

#1258 set the variables in recipe
  cookbooks/bcpc/recipes/graphite.rb
  cookbooks/bcpc/templates/default/carbon/carbon.conf.erb
  cookbooks/bcpc/templates/default/carbon/relay-rules.conf.erb
  cookbooks/bcpc/templates/default/graphite/local_settings.py.erb
Labels: Enhancement, Metrics/Alarming, Ready to Review, Tested, to-backport

#1261 hbase ui binding address
  cookbooks/bcpc-hadoop/recipes/hbase_config.rb
Labels: Enhancement, HBase, Ready To Merge, Tested, to-backport

#1246 Remove float_host from bcpc_kafka
  cookbooks/bcpc_kafka/attributes/default.rb
  cookbooks/bcpc_kafka/libraries/utils.rb
  cookbooks/bcpc_kafka/recipes/kafka.rb
Labels: Kafka
