Repository bloomberg/chef-bach, pull requests merged in 2018-06, with the labels that each got.

#1225 add the activity metrics from hdfs datanode
  cookbooks/bcpc-hadoop/attributes/jmxtrans_agent.rb
Labels: HDFS, Metrics/Alarming, Tested, enhancement, to-backport

#1216 Graphite 112 and zabbix 3
  cookbooks/bach_repository/recipes/graphite.rb
  cookbooks/bcpc/attributes/default.rb
  cookbooks/bcpc/libraries/utils.rb
  cookbooks/bcpc/recipes/graphite.rb
  cookbooks/bcpc/recipes/zabbix-head.rb
  cookbooks/bcpc/templates/default/carbon/carbon.conf.erb
  cookbooks/bcpc/templates/default/graphite/local_settings.py.erb
Labels: Breaking, Metrics/Alarming, Ready to Review, enhancement, to-backport

#1095 Yarn and Datanode alarms
  cookbooks/bcpc-hadoop/recipes/namenode_queries.rb
  cookbooks/bcpc-hadoop/recipes/yarn_config.rb
  cookbooks/bcpc-hadoop/recipes/yarnrm_queries.rb
Labels: Metrics/Alarming, Ready to Review

#1103 found more places that should use active_release
  cookbooks/bach_spark/attributes/default.rb
  cookbooks/bcpc-hadoop/attributes/mapred.rb
  cookbooks/bcpc-hadoop/recipes/namenode_standby.rb
Labels: Ready to Review, Tested, bug

#1056 Set the default jmx datatype to be gauges
  cookbooks/bcpc-hadoop/attributes/jmxtrans_agent.rb
  cookbooks/bcpc-hadoop/templates/default/jmxtrans_agent.xml.erb
Labels: Metrics/Alarming

#1218 Override the Berkshelf solver through the environment
  Berksfile
Labels: Chef

#1230 update HDP 2.6.5.0-292 build version
  .kitchen.yml
  cookbooks/bcpc-hadoop/attributes/default.rb
  cookbooks/bcpc-hadoop/recipes/hdp_repo.rb
  cookbooks/bcpc/attributes/default.rb
Labels: Hadoop, Upstream
