Repository bloomberg/chef-bach, pull requests merged in 2018-05, with the labels that each got.

#1196 Set unique name for Kafka GC logs and set log size
  cookbooks/bcpc_kafka/attributes/default.rb
Labels: Kafka, Tested, enhancement

#1185 updated ambari admin password as part of ambari server setup
  cookbooks/ambari/attributes/default.rb
  cookbooks/ambari/libraries/utils.rb
  cookbooks/ambari/recipes/ambari_server_setup.rb
  cookbooks/ambari/recipes/ambari_views_setup.rb
  cookbooks/bach_ambari/recipes/default.rb
Labels: Tested

#1182 Changes to enable LDAP synchronization
  cookbooks/ambari/attributes/default.rb
  cookbooks/ambari/recipes/ambari_ldap_sync.rb
  cookbooks/ambari/recipes/ambari_server_setup.rb
  cookbooks/ambari/templates/default/ambari.properties.erb
  cookbooks/bach_ambari/attributes/default.rb
  cookbooks/bach_ambari/recipes/default.rb
Labels: Builds, Ready To Merge, Ready to Review, Tested, enhancement

#1198 Deploy custom files/jars to the cluster
  cookbooks/bach_deployment/README.md
  cookbooks/bach_deployment/attributes/default.rb
  cookbooks/bach_deployment/metadata.rb
  cookbooks/bach_deployment/recipes/default.rb
  cookbooks/deployment/README.md
  cookbooks/deployment/attributes/default.rb
  cookbooks/deployment/metadata.rb
  cookbooks/deployment/recipes/default.rb
Labels: Builds, Chef, Ready to Review, Tested, enhancement

#1187 Remove hypervisor's dependency on the Gemfile
  vm-to-cluster.sh
Labels: Hypervisor, Tested

#1192 Silence spurious exception on missing node object in cluster_def
  lib/cluster-def-gem/lib/cluster_def.rb
Labels: Ready to Review, Tested

#1203 Correct fetch_cluster_def behavior when a node_obj is provided
  lib/cluster-def-gem/lib/cluster_def.rb
Labels: Ready to Review, Tested

#1204 Rescurrect repxe to a working state
  repxe_host.rb
Labels: Tested, Tools, to-backport

#1202 Build clusterdef
  cookbooks/bach_repository/.kitchen.yml
  cookbooks/bach_repository/recipes/gems.rb
Labels: Chef, Tested

#1194 Setting HBase GC log file size and number of files for retention
  cookbooks/bcpc-hadoop/recipes/hbase_env.rb
Labels: HBase, Tested, enhancement

#1205 Split gemfiles
  .travis.yml
  CONTRIBUTING.md
  archive_bins.sh
  cluster-assign-roles.sh
  cookbooks/bach_repository/recipes/gems.rb
  gemfiles/bootstrap.gemfile
  gemfiles/hypervisor.gemfile
  gemfiles/nodes.gemfile
  repxe-host.sh
  wait-for-hosts.sh
Labels: Tested, Tools

#1207 Correct broken metadata
  cookbooks/bach_deployment/attributes/default.rb
  cookbooks/hdfsdu/metadata.rb
Labels: Tested, bug

#1210 Revert to #corrected_mac(vm)
  repxe_host.rb
Labels: Tested, to-backport

#1219 Use the HAProxy port for oozie HA
  cookbooks/bcpc-hadoop/recipes/oozie_client.rb
Labels: Oozie
