Repository bloomberg/chef-bach, pull requests merged in 2018-02, with the labels that each got.

#1099 should be active release
  cookbooks/bcpc-hadoop/recipes/configs.rb
Labels: Backport, Hadoop, Ready to Review, bug

#1102 Ensure master and release branches are consistent
  cookbooks/bcpc-hadoop/metadata.rb
Labels: bug

#1101 Set bach_opentsdb version on release-3.0 branch
  cookbooks/bach_opentsdb/metadata.rb
  cookbooks/bcpc-hadoop/metadata.rb
Labels: Backport, bug

#1104 Revert "should be active release"
  cookbooks/bcpc-hadoop/recipes/configs.rb
Labels: bug

#1105 Salvage lints
  cookbooks/bcpc-hadoop/recipes/datanode.rb
  cookbooks/bcpc-hadoop/recipes/namenode_master.rb
  cookbooks/bcpc-hadoop/recipes/region_server.rb
Labels: Ready to Review, Refactor, Tested

#1044 Separate management of client.rb and knife.rb
  cookbooks/bcpc/recipes/chef_client.rb
Labels: Chef, Tested

#1078 Enable phoenix Query Server
  cookbooks/bcpc-hadoop/attributes/phoenixqs.rb
  cookbooks/bcpc-hadoop/recipes/core_site.rb
  cookbooks/bcpc-hadoop/recipes/hbase_config.rb
  cookbooks/bcpc-hadoop/recipes/phoenix_query_server.rb
  cookbooks/bcpc-hadoop/recipes/phoenixqs_hbase_site.rb
  cookbooks/bcpc-hadoop/recipes/phoenixqs_kerberos.rb
  cookbooks/bcpc-hadoop/templates/default/etc_initd_pqs.erb
  stub-environment/environments/Test-Laptop.json
  stub-environment/roles/BCPC-Bootstrap.json
  stub-environment/roles/BCPC-Hadoop-Head-HBase.json
Labels: Phoenix, Ready to Review, Tested

#1090 added alarms for journalnode txid and epoch
  cookbooks/bcpc-hadoop/attributes/journalnode.rb
  cookbooks/bcpc-hadoop/recipes/journalnode.rb
  cookbooks/bcpc-hadoop/recipes/journalnode_queries.rb
Labels: HDFS, Metrics/Alarming, Ready to Review, Tested

#1107 Upgrade to HDP 2.6.3
  cookbooks/bcpc-hadoop/attributes/default.rb
  cookbooks/bcpc/attributes/default.rb
Labels: Builds, Upstream

#1098 Fix issue #1096
  cookbooks/bcpc-hadoop/libraries/utils.rb
Labels: Chef, HBase, bug

#1089 Enable Slider
  cookbooks/bcpc-hadoop/recipes/slider.rb
Labels: Builds, Slider, Tested, YARN, bug

#1113 update sqoop-hive sharelib for HDP 2.6.3
  cookbooks/bcpc-hadoop/recipes/oozie.rb
Labels: Oozie

#1085 upgrade graphite to 1.1.1
  cookbooks/bach_repository/recipes/graphite.rb
  cookbooks/bcpc/recipes/graphite.rb
Labels: Ready to Review, Tested, to-backport

#1117 [HDP] - Upgrade to 2.6.3.22-1 patch release
  cookbooks/bcpc-hadoop/attributes/default.rb
  cookbooks/bcpc/attributes/default.rb
Labels: Builds, Upstream

#1118 Move to sysctl_param and remove sysctl::apply
  cookbooks/bcpc-hadoop/recipes/configs.rb
  cookbooks/bcpc_kafka/recipes/default.rb
Labels: Operating System, Tested, Upstream, bug

#1122 The sysctl include_recipe is still needed for resource collection
  cookbooks/bcpc-hadoop/recipes/configs.rb
  cookbooks/bcpc_kafka/recipes/default.rb
Labels: Chef, Operating System, Tested, bug

#1124 Fix bootstrap_hostname value in graphite queries
  cookbooks/bcpc-hadoop/recipes/graphite_queries.rb
Labels: Chef, Metrics/Alarming, Ready to Review, Tested, bug
