Repository bloomberg/chef-bach, pull requests merged in 2018-10, with the labels that each got.

#1283 Bach web update json page on master
  cookbooks/bcpc-hadoop/attributes/hbase.rb
  cookbooks/bcpc-hadoop/attributes/hdfs.rb
  cookbooks/bcpc-hadoop/recipes/hbase_web.rb
  cookbooks/bcpc-hadoop/recipes/hdfs_web.rb
  cookbooks/bcpc/attributes/apache2.rb
  cookbooks/bcpc/recipes/apache2.rb
  cookbooks/bcpc/templates/default/bach.html.erb
Labels: Enhancement, Tested

#1287 Issue 1286
  cookbooks/bcpc-hadoop/recipes/hbase_master.rb
  cookbooks/bcpc-hadoop/recipes/namenode_master.rb
  cookbooks/bcpc-hadoop/recipes/namenode_no_HA.rb
  cookbooks/bcpc-hadoop/recipes/namenode_standby.rb
Labels: Bug, Builds, Tested

#747 Set spark.dynamicAllocation.maxExecutors
  cookbooks/bach_spark/attributes/default.rb
Labels: Spark

#1285 Allow fair_share_queue overrides
  cookbooks/bcpc-hadoop/libraries/hadoop_helpers.rb
  cookbooks/bcpc-hadoop/recipes/yarn_schedulers.rb
Labels: YARN, to-backport

#1290 Fix for #1288 - Master fails to populate node[:bcpc][:hadoop][:hs_hosts]
  cookbooks/bcpc-hadoop/attributes/default.rb
Labels: Bug, Builds, Oozie, Tested

#1284 Add haproxy hdfs
  cookbooks/bcpc-hadoop/attributes/hbase.rb
  cookbooks/bcpc-hadoop/attributes/hdfs.rb
  cookbooks/bcpc-hadoop/attributes/oozie.rb
  cookbooks/bcpc/attributes/apache2.rb
  cookbooks/bcpc/libraries/utils.rb
  cookbooks/bcpc/recipes/haproxy.rb
Labels: Enhancement, Hadoop, Tested, to-backport

#1291 Correct to Bloomberg's cobbler from mine
  cookbooks/bcpc/Berksfile
Labels: Test

#1293 Finish migrating dir_creation projects default attrs
  cookbooks/bcpc-hadoop/attributes/dir_creation.rb
Labels: Bug, Chef, Tested, to-backport

#1294 Reboot after 10 seconds on kernel panic
  cookbooks/bcpc-hadoop/recipes/configs.rb
Labels: Bug, Operating System, to-backport

#1295 Allow 30 minutes for kdump to write out crash dumps
  cookbooks/bcpc-hadoop/recipes/configs.rb
Labels: Operating System, to-backport

#1296 Update the iPXE efi image from http://boot.ipxe.org
  cookbooks/bcpc/files/default/ipxe-x86_64.efi
Labels: Tested, to-backport
